### ISSUE TITLE
Python path not being recognized

### ISSUE THREAD

**Issue by rishikanthc** [mtshiba/pylyzer#109]
I just installed pylyzer by building it from source. Resolving local imports doesn't seem to work even after setting python path in pyproject.toml. Below is my `pyproject.toml`.

```toml
[tool.poetry]
name = "hdc"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
loguru = "*"
numpy = "*"
einops = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pre-commit = "*"
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylyzer.python]
path = "/Users/rishi/miniconda3/envs/hdc/bin/python"
```

For eg. when I try to import `loguru` I get a `module not found` error.
